export const ngnType = {
    FETCH_NGN_REQUEST: "FETCH_NGN_REQUEST",
    FETCH_NGN_SUCCESS: "FETCH_NGN_SUCCESS",
    FETCH_NGN_FAILURE: "FETCH_NGN_FAILURE",
  };
  
  export const eurType = {
    FETCH_EUR_REQUEST: "FETCH_EUR_REQUEST",
    FETCH_EUR_SUCCESS: "FETCH_EUR_SUCCESS",
    FETCH_EUR_FAILURE: "FETCH_NGN_FAILURE",
  };
  
  export const gbpType = {
    FETCH_GBP_REQUEST: "FETCH_GBP_REQUEST",
    FETCH_GBP_SUCCESS: "FETCH_GBP_SUCCESS",
    FETCH_GBP_FAILURE: "FETCH_GBP_FAILURE",
  };